version: '3.4'

services:
    catalogDb:
        image: mongo

    catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
            context: .
            dockerfile: Services/Catalog/Catalog.API/Dockerfile
volumes:
    mongo_data:

# Docker Compose Run Command: docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d