version: '3.4'

services:
  catalogDb:
    container_name: catalogDb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  basketDb:
    container_name: basketDb
    restart: always
    ports:
      - 6379:6379

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogDb:27017"
      - "DatabaseSettings__DatabaseName=CatalogDb"
      - "DatabaseSettings__ProductsCollection=Products"
      - "DatabaseSettings__BrandsCollection=Brands"
      - "DatabaseSettings__TypesCollection=Types"
    depends_on:
      - catalogDb
    ports:
      - "9000:80"


  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings__ConnectionString=basketDb:6379"
      - "GrpcSettings__DiscountUrl=basketDb:6379"